upload:
	npm run build

# aws s3 cp --recursive build s3://ml-bot/
# aws s3 cp --recursive build s3://ml-bot-dev/
# aws cloudfront create-invalidation --distribution-id E34SNMQONVR1BZ  --paths "/*"
# aws cloudfront create-invalidation --distribution-id E2WHE4NCMJ0GUP  --paths "/*"
