from . import fcn_seg
from . import unet_seg
from . import refinenet_seg
from . import pspnet_seg
from . import encnet_seg
from . import bisenet_seg
from . import fast_scnn_seg
from . import icnet_seg
from . import deeplabv3
from . import deeplabv3_plus
from . import mobilenet_deeplabv3_plus
from . import mobilev2_fcn_seg
from . import r2_unet_seg
from . import r2_attention_unet_seg
from . import attention_unet_seg
