.PHONY: build up start stop down status bash

build:
	docker-compose build

up:
	docker-compose up -d

start:
	docker-compose start

stop:
	docker-compose stop

down:
	docker-compose down

status:
	docker-compose ps

bash:
	docker-compose exec web /bin/bash